'use client';
import {useEffect,useState} from 'react';
import {CircleDollarSign,Clock3,History,LayoutDashboard,Settings,Play,Square,Calculator,Pencil,Trash2,X,Check,Menu,Users} from 'lucide-react';
import type {State,Session,Table} from '@/lib/types';
const KEY='rackCueNext.v1';
const initial:State={settings:{snooker:260,pool:200},tables:[{id:1,type:'Snooker',rateKey:'snooker',active:null},{id:2,type:'Pool',rateKey:'pool',active:null}],history:[]};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n);
const dateVal=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const timeVal=(d=new Date())=>`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;
const parse=(d:string,t:string)=>new Date(`${d}T${t}:00`).getTime();
const dur=(ms:number)=>{let s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60),sec=s%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};
const human=(ms:number)=>{const mins=Math.round(ms/60000),h=Math.floor(mins/60),m=mins%60;return h?`${h}h ${m}m`:`${m}m`};
const fmtDate=(s:string)=>new Date(`${s}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const fmtTime=(s:string)=>{const [h,m]=s.split(':').map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})};
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function calc(start:number,stop:number,rate:number){const ms=stop-start;if(ms<0)throw Error('Stop time cannot be before start time.');return {durationMs:ms,amount:(ms/3600000)*rate}}
function Button({children,className='',...p}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition active:scale-[.98] disabled:opacity-50 ${className}`} {...p}>{children}</button>}
function Field({label,...p}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span><input className="h-11 rounded-xl border border-slate-200 bg-white px-3 outline-none focus:border-slate-400" {...p}/></label>}
export default function Dashboard(){
 const [state,setState]=useState<State>(initial),[view,setView]=useState<'dashboard'|'history'|'settings'>('dashboard'),[now,setNow]=useState(Date.now()),[modal,setModal]=useState<any>(null),[toast,setToast]=useState(''),[mobile,setMobile]=useState(false);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'');if(x?.tables&&x?.settings&&x?.history)setState(x)}catch{}},[]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(state))},[state]);
 useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);
 useEffect(()=>{if(toast){const i=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(i)}},[toast]);
 const today=dateVal();const todays=state.history.filter(x=>x.stopDate===today);const revenue=todays.reduce((a,x)=>a+x.amount,0),play=todays.reduce((a,x)=>a+x.durationMs,0);
 const start=(table:Table)=>{const d=new Date();setModal({kind:'start',table,customer:'',phone:'',date:dateVal(d),time:timeVal(d)})};
 const confirmStart=()=>{if(!modal.customer.trim())return setToast('Customer name is required');const ts=parse(modal.date,modal.time);if(!Number.isFinite(ts))return setToast('Invalid start date/time');setState(s=>({...s,tables:s.tables.map(t=>t.id===modal.table.id?{...t,active:{id:uid(),customer:modal.customer.trim(),phone:modal.phone.trim(),startTs:ts}}:t)}));setModal(null);setToast('Session started')};
 const previewActive=(t:Table)=>{if(!t.active)return;try{const c=calc(t.active.startTs,Date.now(),state.settings[t.rateKey]);setState(s=>({...s,tables:s.tables.map(x=>x.id===t.id&&x.active?{...x,active:{...x.active,preview:c}}:x)}))}catch(e){setToast((e as Error).message)}};
 const stop=(t:Table)=>{if(!t.active)return;const d=new Date();setModal({kind:'stop',table:t,rate:state.settings[t.rateKey],customer:t.active.customer,phone:t.active.phone,startDate:dateVal(new Date(t.active.startTs)),startTime:timeVal(new Date(t.active.startTs)),stopDate:dateVal(d),stopTime:timeVal(d),calculated:null})};
 const calculateStop=()=>{try{const a=parse(modal.startDate,modal.startTime),b=parse(modal.stopDate,modal.stopTime),c=calc(a,b,modal.rate);setModal({...modal,calculated:c})}catch(e){setToast((e as Error).message)}};
 const confirmStop=()=>{if(!modal.calculated)return setToast('Click Calculate Amount first');const startTs=parse(modal.startDate,modal.startTime),stopTs=parse(modal.stopDate,modal.stopTime);const session:Session={id:modal.table.active.id,tableId:modal.table.id,type:modal.table.type,customer:modal.customer.trim(),phone:modal.phone.trim(),startDate:modal.startDate,startTime:modal.startTime,stopDate:modal.stopDate,stopTime:modal.stopTime,startTs,stopTs,durationMs:modal.calculated.durationMs,rate:modal.rate,amount:modal.calculated.amount};setState(s=>({...s,tables:s.tables.map(t=>t.id===modal.table.id?{...t,active:null}:t),history:[...s.history,session]}));setModal(null);setToast('Session saved')};
 const edit=(x:Session)=>setModal({kind:'edit',table:{id:x.tableId,type:x.type},session:x,rate:x.rate,customer:x.customer,phone:x.phone,startDate:x.startDate,startTime:x.startTime,stopDate:x.stopDate,stopTime:x.stopTime,calculated:null});
 const calculateEdit=()=>{try{const c=calc(parse(modal.startDate,modal.startTime),parse(modal.stopDate,modal.stopTime),modal.rate);setModal({...modal,calculated:c})}catch(e){setToast((e as Error).message)}};
 const saveEdit=()=>{if(!modal.calculated)return setToast('Click Calculate Amount first');setState(s=>({...s,history:s.history.map(x=>x.id===modal.session.id?{...x,customer:modal.customer.trim(),phone:modal.phone.trim(),startDate:modal.startDate,startTime:modal.startTime,stopDate:modal.stopDate,stopTime:modal.stopTime,startTs:parse(modal.startDate,modal.startTime),stopTs:parse(modal.stopDate,modal.stopTime),durationMs:modal.calculated.durationMs,amount:modal.calculated.amount}:x)}));setModal(null);setToast('Changes saved')};
 const del=(id:string)=>{if(confirm('Delete this completed session?')){setState(s=>({...s,history:s.history.filter(x=>x.id!==id)}));setToast('Session deleted')}};
 const nav=(v:'dashboard'|'history'|'settings')=>{setView(v);setMobile(false)};
 return <div className="min-h-screen bg-[#f6f7f9]">
  <aside className={`fixed inset-y-0 left-0 z-30 w-64 border-r border-slate-200 bg-white p-5 transition-transform lg:translate-x-0 ${mobile?'translate-x-0':'-translate-x-full'}`}><div className="mb-8 flex items-center justify-between"><div><div className="text-xl font-black tracking-tight">Rack & Cue</div><div className="text-xs text-slate-500">Table Management</div></div><button className="lg:hidden" onClick={()=>setMobile(false)}><X/></button></div><div className="grid gap-1">{[['dashboard','Dashboard',LayoutDashboard],['history','History',History],['settings','Settings',Settings]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>nav(id)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold ${view===id?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-100'}`}><Icon size={18}/>{label}</button>)}</div><div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-slate-50 p-4 text-xs text-slate-500">2 tables · Snooker ₹{state.settings.snooker}/hr · Pool ₹{state.settings.pool}/hr</div></aside>
  {mobile&&<div className="fixed inset-0 z-20 bg-black/30 lg:hidden" onClick={()=>setMobile(false)}/>}<main className="lg:pl-64"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8"><header className="mb-6 flex items-center justify-between"><div className="flex items-center gap-3"><button className="rounded-xl border border-slate-200 bg-white p-2 lg:hidden" onClick={()=>setMobile(true)}><Menu size={20}/></button><div><h1 className="text-2xl font-black tracking-tight">{view==='dashboard'?'Dashboard':view==='history'?'Session History':'Settings'}</h1><p className="mt-1 text-sm text-slate-500">{view==='dashboard'?'Live table status and today’s performance':'Manage your club records and rates'}</p></div></div></header>
  {view==='dashboard'&&<><div className="mb-6 grid gap-4 md:grid-cols-3"><Stat icon={CircleDollarSign} label="Today's Revenue" value={money(revenue)}/><Stat icon={Users} label="Today's Sessions" value={String(todays.length)}/><Stat icon={Clock3} label="Today's Playing Time" value={human(play)}/></div><div className="grid gap-5 md:grid-cols-2">{state.tables.map(t=><TableCard key={t.id} t={t} rate={state.settings[t.rateKey]} now={now} onStart={()=>start(t)} onCalc={()=>previewActive(t)} onStop={()=>stop(t)}/>)}</div></>}
  {view==='history'&&<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Customer','Phone','Table','Type','Start','Stop','Duration','Rate','Amount',''].map(h=><th key={h} className="px-4 py-3 text-left font-bold">{h}</th>)}</tr></thead><tbody>{state.history.length===0?<tr><td colSpan={10} className="px-4 py-16 text-center text-slate-500">No completed sessions yet.</td></tr>:state.history.slice().reverse().map(x=><tr key={x.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{x.customer}</td><td className="px-4 py-3">{x.phone||'—'}</td><td className="px-4 py-3">Table {x.tableId}</td><td className="px-4 py-3">{x.type}</td><td className="px-4 py-3">{fmtDate(x.startDate)} · {fmtTime(x.startTime)}</td><td className="px-4 py-3">{fmtDate(x.stopDate)} · {fmtTime(x.stopTime)}</td><td className="px-4 py-3 tabular">{human(x.durationMs)}</td><td className="px-4 py-3">{money(x.rate)}/h</td><td className="px-4 py-3 font-bold">{money(x.amount)}</td><td className="px-4 py-3"><div className="flex gap-2"><Button className="bg-slate-100" onClick={()=>edit(x)} aria-label="Edit session"><Pencil size={15}/></Button><Button className="bg-red-50 text-red-600" onClick={()=>del(x.id)} aria-label="Delete session"><Trash2 size={15}/></Button></div></td></tr>)}</tbody></table></div></div>}
  {view==='settings'&&<SettingsPanel state={state} setState={setState} onToast={setToast}/>} 
  </div></main>
  {modal&&<Modal modal={modal} setModal={setModal} confirmStart={confirmStart} calculateStop={calculateStop} confirmStop={confirmStop} calculateEdit={calculateEdit} saveEdit={saveEdit}/>} {toast&&<div className="fixed bottom-5 right-5 z-50 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white shadow-xl">{toast}</div>}
 </div>
}
function Stat({icon:Icon,label,value}:any){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><Icon size={19}/></div><div className="text-sm text-slate-500">{label}</div><div className="mt-1 text-2xl font-black tabular">{value}</div></div>}
function TableCard({t,rate,now,onStart,onCalc,onStop}:any){const a=t.active;return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="flex items-start justify-between"><div><div className="text-xl font-black">{t.type} Table</div><div className="mt-1 text-sm text-slate-500">{money(rate)} / hour</div></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${a?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{a?'● ACTIVE':'○ AVAILABLE'}</span></div>{a?<><div className="mt-8"><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">Customer</div><div className="mt-1 text-2xl font-black">{a.customer}</div>{a.phone&&<div className="mt-1 text-sm text-slate-500">{a.phone}</div>}<div className="mt-4 text-sm text-slate-500">Started {new Date(a.startTs).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}</div><div className="mt-2 text-4xl font-black tabular tracking-tight">{dur(now-a.startTs)}</div>{a.preview&&<div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4"><div className="text-sm text-slate-600">Calculated duration <b>{human(a.preview.durationMs)}</b></div><div className="mt-1 text-xl font-black">{money(a.preview.amount)}</div></div>}</div><div className="mt-6 flex flex-wrap gap-2"><Button className="bg-slate-900 text-white" onClick={onCalc}><Calculator size={17}/>Calculate Amount</Button><Button className="bg-red-50 text-red-600" onClick={onStop}><Square size={16}/>Stop Session</Button></div></>:<div className="flex min-h-[250px] flex-col items-center justify-center"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-slate-100"><Play size={25}/></div><Button className="bg-slate-900 text-white" onClick={onStart}><Play size={17}/>Start Session</Button></div>}</section>}
function SettingsPanel({state,setState,onToast}:any){const [snooker,setSnooker]=useState(state.settings.snooker),[pool,setPool]=useState(state.settings.pool);useEffect(()=>{setSnooker(state.settings.snooker);setPool(state.settings.pool)},[state.settings.snooker,state.settings.pool]);const save=()=>{if(!Number.isFinite(snooker)||snooker<=0||!Number.isFinite(pool)||pool<=0)return onToast('Enter valid rates');setState((s:State)=>({...s,settings:{snooker,pool}}));onToast('Settings saved')};return <div className="max-w-xl rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><h2 className="mb-1 text-lg font-bold">Hourly Rates</h2><p className="mb-6 text-sm text-slate-500">Changing rates affects new sessions only. Saved sessions retain their original rate.</p><div className="grid gap-4"><Field label="Snooker hourly rate (₹)" type="number" min="0.01" step="0.01" value={snooker} onChange={e=>setSnooker(Number(e.target.value))}/><Field label="Pool hourly rate (₹)" type="number" min="0.01" step="0.01" value={pool} onChange={e=>setPool(Number(e.target.value))}/><Button className="w-fit bg-slate-900 text-white" onClick={save}><Check size={17}/>Save Settings</Button></div></div>}
function Modal({modal,setModal,confirmStart,calculateStop,confirmStop,calculateEdit,saveEdit}:any){const isStart=modal.kind==='start',isStop=modal.kind==='stop',m=modal;return <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-xl font-black">{isStart?'Start Session':isStop?'Stop Session':'Edit Session'}</h2><p className="mt-1 text-sm text-slate-500">{m.table.type} Table</p></div><button onClick={()=>setModal(null)} className="rounded-xl p-2 hover:bg-slate-100"><X/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Customer Name" required value={m.customer} onChange={e=>setModal({...m,customer:e.target.value})}/><Field label="Phone Number" value={m.phone} onChange={e=>setModal({...m,phone:e.target.value})}/><Field label="Start Date" type="date" value={m.date||m.startDate} onChange={e=>setModal({...m,[isStart?'date':'startDate']:e.target.value,calculated:isStart?m.calculated:null})}/><Field label="Start Time" type="time" value={m.time||m.startTime} onChange={e=>setModal({...m,[isStart?'time':'startTime']:e.target.value,calculated:isStart?m.calculated:null})}/>{!isStart&&<><Field label="Stop Date" type="date" value={m.stopDate} onChange={e=>setModal({...m,stopDate:e.target.value,calculated:null})}/><Field label="Stop Time" type="time" value={m.stopTime} onChange={e=>setModal({...m,stopTime:e.target.value,calculated:null})}/></>}</div>{!isStart&&<div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="text-sm text-slate-500">Rate used</div><div className="font-bold">{money(m.rate)}/hour</div>{m.calculated&&<div className="mt-3 grid grid-cols-2 gap-4"><div><div className="text-xs text-slate-500">Duration</div><div className="text-lg font-black">{human(m.calculated.durationMs)}</div></div><div><div className="text-xs text-slate-500">Amount</div><div className="text-lg font-black">{money(m.calculated.amount)}</div></div></div>}</div>}<div className="mt-6 flex flex-wrap justify-end gap-2"><Button className="bg-slate-100" onClick={()=>setModal(null)}>Cancel</Button>{isStart?<Button className="bg-slate-900 text-white" onClick={confirmStart}>Start Session</Button>:<><Button className="bg-blue-50 text-blue-700" onClick={isStop?calculateStop:calculateEdit}><Calculator size={17}/>Calculate Amount</Button><Button className="bg-slate-900 text-white" onClick={isStop?confirmStop:saveEdit}>{isStop?'Confirm & Save Session':'Save Changes'}</Button></>}</div></div></div>}
